name: ci
on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.x

jobs:
  deploy:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:

      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download videos branch and unzip
        run: |
          wget https://codeload.github.com/MiSTer-devel/MkDocs_MiSTer/zip/refs/heads/videos
          unzip videos
          cd MkDocs_MiSTer-videos/
          cp -r docs ../

      - name: Setup Python runtime
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy Documentation
        run: |
          mkdocs gh-deploy --force
          mkdocs --version
